### ISSUE TITLE
Full outer join with CTE causes NullReference

### ISSUE THREAD

**Issue by terrajobst** [terrajobst/nquery#10]
_Ported from CodePlex_

``` SQL
WITH D AS (
 SELECT o.OrderDate,
   od.Quantity * od.UnitPrice * (1 - od.Discount) AS Price
 FROM Orders o,
   [Order Details] od
 WHERE od.OrderID = o.OrderID
)
SELECT *
FROM D AS D1
   FULL JOIN D AS D2 ON D1.OrderDate >= D2.OrderDate
```

Replacing the join type by an inner join or replacing the `>=` by the `=` works fine.

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at NQuery.Compilation.HashMatchAlgebraNode.Clone(Dictionary`2 alreadyClonedElements) in N:\Trunk\Src\NQuery\AST\Algebra\HashMatchAlgebraNode.cs:line 66
>    at NQuery.Compilation.AstElement.Clone() in N:\Trunk\Src\NQuery\AST\AstElement.cs:line 18
>    at NQuery.Compilation.FullOuterJoinExpander.VisitJoinAlgebraNode(JoinAlgebraNode node) in N:\Trunk\Src\NQuery\Compilation\FullOuterJoinExpander.cs:line 19
>    at NQuery.Compilation.StandardVisitor.Visit(AstNode node) in N:\Trunk\Src\NQuery\AST\Visitor\StandardVisitor.cs:line 84
>    at NQuery.Compilation.StandardVisitor.VisitAlgebraNode(AlgebraNode node) in N:\Trunk\Src\NQuery\AST\Visitor\StandardVisitor.cs:line 409
>    at NQuery.Compilation.StandardVisitor.VisitResultAlgebraNode(ResultAlgebraNode node) in N:\Trunk\Src\NQuery\AST\Visitor\StandardVisitor.cs:line 503
>    at NQuery.Compilation.StandardVisitor.Visit(AstNode node) in N:\Trunk\Src\NQuery\AST\Visitor\StandardVisitor.cs:line 102
>    at NQuery.Compilation.Compiler.PhaseCollection.<>c__DisplayClass6.<Add>b__5(AstNode input) in N:\Trunk\Src\NQuery\Compilation\Compiler.cs:line 95
>    at NQuery.Compilation.Compiler.PhaseRunner.Run() in N:\Trunk\Src\NQuery\Compilation\Compiler.cs:line 118
>    at NQuery.Compilation.Compiler.CompileQuery(String queryText, Scope scope) in N:\Trunk\Src\NQuery\Compilation\Compiler.cs:line 199
>    at NQuery.Query.Compile() in N:\Trunk\Src\NQuery\API\Query.cs:line 90
>    at NQuery.Query.EnsureCompiled() in N:\Trunk\Src\NQuery\API\Query.cs:line 75
>    at NQuery.Query.ExecuteDataTable() in N:\Trunk\Src\NQuery\API\Query.cs:line 127
>    at NQuery.Gui.QueryDocument.Execute() in N:\Trunk\Src\NQuery.Gui\QueryDocument.cs:line 196
>    at NQuery.Gui.QueryDocument.NQuery.Gui.IQueryHandler.Execute() in N:\Trunk\Src\NQuery.Gui\QueryDocument.cs:line 135
>    at NQuery.Gui.MainForm.executeToolStripButton_Click(Object sender, EventArgs e) in N:\Trunk\Src\NQuery.Gui\MainForm.cs:line 383
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by dallmair** [comment]
Works fine in v.Next (result also looks good to me).
