### ISSUE TITLE
Compilation errors should reveal full error information

### ISSUE THREAD

**Issue by terrajobst** [terrajobst/nquery#2]
_Ported from CodePlex_

In some cases, the NQuery `CompilationException` does NOT carry the full error information.

For example, when a PropertyBinding can't get the value of the associated property, the observed exception is as follows:

> NQuery.CompilationException: Expression could not be compiled. Cannot evaluate constant expression: PropertyBinding.GetValue() threw an exception.
> at NQuery.Expression`1.Compile()
> at NQuery.Expression`1.Evaluate()
> at MyCode()

The important part, namely the caught exception, is missing.

**Comment by dallmair** [comment]
Works fine in v.Next.
