### ISSUE TITLE
ArgumentOutOfRangeException when positioning the caret in query editor

### ISSUE THREAD

**Issue by terrajobst** [terrajobst/nquery#8]
_Ported from CodePlex_

Some of our users create queries with very long lines in an automated fashion and then cut and paste those into a query editor window which is based on the NQuery ActiproLink implementation. When they try to position the caret at the end of such a long line, they experience the following exception:

> Argument 'column' is out-of-range (0-2047), actual value was 4523.
> Parameter name: column
> Actual value was 4523. (NQuery)
> 
> Program Location:
> 
>   at NQuery.SourceLocation..ctor(Int32 column, Int32 line)
>    at NQuery.UI.ActiproLink.get_CurrentLocation()
>    at NQuery.UI.ActiproLink.UpdateParameterInfo()
>    at ActiproSoftware.SyntaxEditor.SelectionEventHandler.Invoke(Object sender, SelectionEventArgs e)
>    at ActiproSoftware.SyntaxEditor.SyntaxEditor.OnSelectionChanged(SelectionEventArgs e)
>    at ActiproSoftware.SyntaxEditor.SyntaxEditor.a(SelectionEventArgs A_0)
>    at ActiproSoftware.SyntaxEditor.EditorView.a(Object A_0, SelectionEventArgs A_1)
>    at ActiproSoftware.SyntaxEditor.Selection.a(SelectionEventArgs A_0)
>    at ActiproSoftware.SyntaxEditor.Selection.b(Boolean A_0)
>    at ActiproSoftware.SyntaxEditor.Selection.a(DocumentModificationEventArgs A_0)
>    at ActiproSoftware.SyntaxEditor.SyntaxEditor.d(Object A_0, DocumentModificationEventArgs A_1)
>    at ActiproSoftware.SyntaxEditor.Document.b(DocumentModificationEventArgs A_0)
>    at ActiproSoftware.SyntaxEditor.Document.a(DocumentModification A_0, Boolean A_1)
>    at ActiproSoftware.SyntaxEditor.Document.b(DocumentModificationType A_0, Int32 A_1, Int32 A_2, String A_3, DocumentModificationOptions A_4, WeakReference A_5)
>    at ActiproSoftware.SyntaxEditor.Document.a(DocumentModificationType A_0, Int32 A_1, Int32 A_2, DocumentModificationOptions A_3, WeakReference A_4)
>    at ActiproSoftware.SyntaxEditor.Commands.BackspaceCommand.Execute(EditCommandContext context)
>    at ActiproSoftware.SyntaxEditor.MacroRecording.a(EditCommand A_0, EditCommandContext A_1)
>    at ActiproSoftware.SyntaxEditor.EditorView.a(EditCommand A_0, Boolean A_1)
>    at ActiproSoftware.SyntaxEditor.SyntaxEditor.a(EditorView A_0, Keys A_1, Char A_2, Boolean A_3)
>    at ActiproSoftware.SyntaxEditor.SyntaxEditor.OnKeyDown(KeyEventArgs e)
>    at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
>    at System.Windows.Forms.Control.WmKeyChar(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at ActiproSoftware.SyntaxEditor.SyntaxEditor.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Background: The `SourceLocation` structure stores both line and column information in a single integer with 11 bits reserved for the column information. Although 2048 (2^11) characters might seem much for a single line, it quickly becomes a limitation with those generated queries.

From my point of view there are three options:
1. Assign more bits in the `SourceLocation` integer to the column index. A 16/16 split would allow for 65536 lines with 65536 characters per line -- with this partitioning scheme it shouldn't matter whether the queries are generated with long lines or many lines.
2. Store the information in an Int64 field. Probably a 32/32 split would be best in this case.
3. Store the information in two Int32 fields.

**Comment by dallmair** [comment]
Works fine in v.Next. The new TextSpan uses two Int32 properties.
